;This is the description of the Loto loot table
[adult]
round = 10
quine = 100
double_quine = 200
carton = 350
gros_lot = 770
pas_de_bol = 300

[kid]
round = 4
quine = 100
double_quine = 200
carton = 300
gros_lot = 280
pas_de_bol = 400
