;This is the description of the Loto loot table
[adult]
round = 11
quine = 100
double_quine = 200
carton = 350
gros_lot = 1000
pas_de_bol = 400

[kid]
round = 4
quine = 100
double_quine = 200
carton = 280
gros_lot = 300
pas_de_bol = 150
