;This is the description of the Loto loot table
[adult]
round = 13
quine = 80
double_quine = 130
carton = 280
gros_lot = 1000
pas_de_bol = 400

[kid]
round = 6
quine = 50
double_quine = 100
carton = 200
gros_lot = 300
pas_de_bol = 150
